resilience4j:
  ratelimiter:
    instances:
      apiLimiter:
        limit-for-period: 3
        limit-refresh-period: 10s
        timeout-duration: 0

logging:
  level:
    org.springframework.aop: DEBUG
    io.github.resilience4j: DEBUG
